# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh sách bác sỹ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DoctorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=500, verbose_name='Tên')),
                ('level', models.CharField(max_length=500, verbose_name='Học hàm học vị')),
                ('description', models.CharField(max_length=2000, verbose_name='Mô tả')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web.Doctor')),
            ],
            options={
                'default_permissions': (),
                'db_tablespace': '',
                'verbose_name': 'Danh sách bác sỹ Translation',
                'db_table': 'web_doctor_translation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('image', models.ImageField(upload_to='upload/images')),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide ảnh',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SlideTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tiêu đề')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Mô tả')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web.Slide')),
            ],
            options={
                'default_permissions': (),
                'db_tablespace': '',
                'verbose_name': 'Slide ảnh Translation',
                'db_table': 'web_slide_translation',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='slidetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='doctortranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
