# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Danh sách bác sỹ', 'verbose_name_plural': 'Danh sách bác sỹ'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide ảnh', 'verbose_name_plural': 'Slide ảnh'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='upload/images'),
            preserve_default=False,
        ),
    ]
